development: &default
  adapter: postgresql
  encoding: unicode
  database: your-project_development
  pool: 5
  username: <%= ENV.fetch('DB_USERNAME', 'your-project') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'your-project') %>
  host: <%= ENV.fetch('DB_1_PORT_5432_TCP_ADDR', 'localhost') %>
  port: <%= ENV.fetch('DB_1_PORT_5432_TCP_PORT', '5432') %>
 
test: &test
  <<: *default
  database: your-project_test
